# List of the vs code extensions
vscode:
  extensions:
    - ms-python.python
    - ms-vscode.live-server

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: sudo apt-get install python3-dev -y && pip install -r requirements.txt
    openMode: split-right