# List of the vs code extensions
vscode:
  extensions:
    - ms-python.python

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: pip install -r requirements.txt
    openMode: split-right